version: '3.4'

services:
  rabbitmq:
    image: ${DOCKER_REGISTRY-}rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
        - 15674:15674
    build:
      context: .
      dockerfile: Dockerfile   
